config/routes.rb
Rails.application.routes.draw do
  get 'high_chart/index'
  get 'high_chart/line_charts'
  get 'high_chart/area_charts'
  get 'high_chart/column_and_bar_charts'
  get 'high_chart/pie_charts'
  get 'high_chart/scatter_and_bubble_charts'
  get 'high_chart/combinations'
  get 'high_chart/styled_mode'
  get 'high_chart/accessible_charts'
  get 'high_chart/dynamic_charts'
  get 'high_chart/three_d_charts'
  get 'high_chart/gauges'
  get 'high_chart/heat_and_tree_maps'
  get 'high_chart/more_chart_types'
  get 'charts/index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
  end
end

app/controllers/high_chart_controller.rb
class HighChartController < ApplicationController
  def index
  end

  def line_charts
  end

  def area_charts
  end

  def column_and_bar_charts
  end

  def pie_charts
  end

  def scatter_and_bubble_charts
  end

  def combinations
  end

  def styled_mode
  end

  def accessible_charts
  end

  def dynamic_charts
  end

  def three_d
  end

  def gauges
  end

  def heat_and_tree_maps
  end

  def more_chart_types
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/high_chart_helper.rb
module HighChartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charts/index.html.erb
<h1>List of Chart Providers</h1>
<ul>
    <li>
        With Gem
        <ul>
            <li><strong><%= link_to 'highcharts-rails - (Active -> Please Click on this link)', high_chart_index_path %></strong></li>
            <li><%= link_to 'Chartkick - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'gruff - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'lazy_high_charts - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'open_flash_chart - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'google_visualr - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'gnuplot - (In Active -> Coming Soon)', '/' %></li>
            <li><%= link_to 'googlecharts - (In Active -> Coming Soon)', '/' %></li>
        </ul>
    </li>
    <li>Without Gem</li>
</ul

app/views/high_chart/accessible_charts.html.erb
<h1>HighChart#accessible_charts</h1>
<p>Find me in app/views/high_chart/accessible_charts.html.erb</p>

app/views/high_chart/area_charts.html.erb
<h1>HighChart#area_charts</h1>
<p>Find me in app/views/high_chart/area_charts.html.erb</p>

app/views/high_chart/column_and_bar_charts.html.erb
<h1>HighChart#column_and_bar_charts</h1>
<p>Find me in app/views/high_chart/column_and_bar_charts.html.erb</p>

app/views/high_chart/combinations.html.erb
<h1>HighChart#combinations</h1>
<p>Find me in app/views/high_chart/combinations.html.erb</p>

app/views/high_chart/dynamic_charts.html.erb
<h1>HighChart#dynamic_charts</h1>
<p>Find me in app/views/high_chart/dynamic_charts.html.erb</p>

app/views/high_chart/gauges.html.erb
<h1>HighChart#gauges</h1>
<p>Find me in app/views/high_chart/gauges.html.erb</p>

app/views/high_chart/heat_and_tree_maps.html.erb
<h1>HighChart#heat_and_tree_maps</h1>
<p>Find me in app/views/high_chart/heat_and_tree_maps.html.erb</p>

app/views/high_chart/index.html.erb
<h1>List of High Chart Types</h1>
<ul>
    <li><strong><%= link_to 'Line Charts - (Active -> Please Click on this link)', high_chart_line_charts_path %></strong></li>
    <li><%= link_to 'Area Charts - (In Active -> Coming Soon)', high_chart_area_charts_path %></li>
    <li><%= link_to 'Column And Bar Charts - (In Active -> Coming Soon)', high_chart_column_and_bar_charts_path %></li>
    <li><%= link_to 'Pie Charts - (In Active -> Coming Soon)', high_chart_pie_charts_path %></li>
    <li><%= link_to 'Scatter And Bubble Charts - (In Active -> Coming Soon)', high_chart_scatter_and_bubble_charts_path %></li>
    <li><%= link_to 'Combinations - (In Active -> Coming Soon)', high_chart_combinations_path %></li>
    <li><%= link_to 'Styled Mode - (In Active -> Coming Soon)', high_chart_styled_mode_path %></li>
    <li><%= link_to 'Accessible Charts - (In Active -> Coming Soon)', high_chart_accessible_charts_path %></li>
    <li><%= link_to 'Dynamic Charts - (In Active -> Coming Soon)', high_chart_dynamic_charts_path %></li>
    <li><%= link_to '3D Charts - (In Active -> Coming Soon)', high_chart_three_d_charts_path %></li>
    <li><%= link_to 'Gauges - (In Active -> Coming Soon)', high_chart_gauges_path %></li>
    <li><%= link_to 'Heat And Tree Maps - (In Active -> Coming Soon)', high_chart_heat_and_tree_maps_path %></li>
    <li><%= link_to 'More Chart Types - (In Active -> Coming Soon)', high_chart_more_chart_types_path %></li>
</ul>

app/views/high_chart/line_charts.html.erb
<br />
<h1>Line_charts</h1>
<br />
<br />
<ul>
    <li>
        <h2><strong><u>Basic line</u></strong></h2>
        <%= render 'high_chart/line_charts/basic_line' %>
    </li>
    <li>
        <h2><strong><u>Ajax loaded data, clickable points</u></strong></h2>
        <%= render 'high_chart/line_charts/ajax_loaded_data' %>
    </li>
    <li>
        <h2><strong><u>Line chart with 500k points</u></strong></h2>
        <%= render 'high_chart/line_charts/with_500_k_points' %>
    </li>
    <li>
        <h2><strong><u>Logarithmic axis</u></strong></h2>
        <%= render 'high_chart/line_charts/logarithmic_axis' %>
    </li>
    <li>
        <h2><strong><u>Spline with inverted axes</u></strong></h2>
        <%= render 'high_chart/line_charts/spline_with_inverted_axes' %>
    </li>
    <li>
        <h2><strong><u>Spline with plot bands</u></strong></h2>
        <%= render 'high_chart/line_charts/spline_with_plot_bands' %>
    </li>
    <li>
        <h2><strong><u>Spline with symbols</u></strong></h2>
        <%= render 'high_chart/line_charts/spline_with_symbols' %>
    </li>
    <li>
        <h2><strong><u>Time data with irregular intervals</u></strong></h2>
        <%= render 'high_chart/line_charts/time_data_with_irregular_intervals' %>
    </li>
    <li>
        <h2><strong><u>Time series, zoomable</u></strong></h2>
        <%= render 'high_chart/line_charts/time_series_zoomable' %>
    </li>
    <li>
        <h2><strong><u>With annotations</u></strong></h2>
        <%= render 'high_chart/line_charts/with_annotations' %>
    </li>
    <li>
        <h2><strong><u>With data labels</u></strong></h2>
        <%= render 'high_chart/line_charts/with_data_labels' %>
    </li>
</ul>

app/views/high_chart/line_charts/_ajax_loaded_data.html.erb
<br />
<br />
<figure class="highcharts-figure">
    <div id="high_chart_line_charts_ajax_loaded_data"></div>
    <p class="highcharts-description">
        Chart showing data loaded dynamically. The individual data points can
        be clicked to display more information.
    </p>
</figure>
<br />
<br />
<hr />

<script>
    Highcharts.addEvent(Highcharts.Point, 'click', function () {
        if (this.series.options.className.indexOf('popup-on-click') !== -1) {
            const chart = this.series.chart;
            const date = Highcharts.dateFormat('%A, %b %e, %Y', this.x);
            const text = `<b>${date}</b><br/>${this.y} ${this.series.name}`;

            const anchorX = this.plotX + this.series.xAxis.pos;
            const anchorY = this.plotY + this.series.yAxis.pos;
            const align = anchorX < chart.chartWidth - 200 ? 'left' : 'right';
            const x = align === 'left' ? anchorX + 10 : anchorX - 10;
            const y = anchorY - 30;
            if (!chart.sticky) {
                chart.sticky = chart.renderer
                    .label(text, x, y, 'callout',  anchorX, anchorY)
                    .attr({
                        align,
                        fill: 'rgba(0, 0, 0, 0.75)',
                        padding: 10,
                        zIndex: 7 // Above series, below tooltip
                    })
                    .css({
                        color: 'white'
                    })
                    .on('click', function () {
                        chart.sticky = chart.sticky.destroy();
                    })
                    .add();
            } else {
                chart.sticky
                    .attr({ align, text })
                    .animate({ anchorX, anchorY, x, y }, { duration: 250 });
            }
        }
    });


    Highcharts.chart('high_chart_line_charts_ajax_loaded_data', {

        chart: {
            scrollablePlotArea: {
                minWidth: 700
            }
        },

        data: {
            csvURL: 'https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/analytics.csv',
            beforeParse: function (csv) {
                return csv.replace(/\n\n/g, '\n');
            }
        },

        title: {
            text: 'Daily sessions at www.highcharts.com'
        },

        subtitle: {
            text: 'Source: Google Analytics'
        },

        xAxis: {
            tickInterval: 7 * 24 * 3600 * 1000, // one week
            tickWidth: 0,
            gridLineWidth: 1,
            labels: {
                align: 'left',
                x: 3,
                y: -3
            }
        },

        yAxis: [{ // left y axis
            title: {
                text: null
            },
            labels: {
                align: 'left',
                x: 3,
                y: 16,
                format: '{value:.,0f}'
            },
            showFirstLabel: false
        }, { // right y axis
            linkedTo: 0,
            gridLineWidth: 0,
            opposite: true,
            title: {
                text: null
            },
            labels: {
                align: 'right',
                x: -3,
                y: 16,
                format: '{value:.,0f}'
            },
            showFirstLabel: false
        }],

        legend: {
            align: 'left',
            verticalAlign: 'top',
            borderWidth: 0
        },

        tooltip: {
            shared: true,
            crosshairs: true
        },

        plotOptions: {
            series: {
                cursor: 'pointer',
                className: 'popup-on-click',
                marker: {
                    lineWidth: 1
                }
            }
        },

        series: [{
            name: 'All sessions',
            lineWidth: 4,
            marker: {
                radius: 4
            }
        }, {
            name: 'New users'
        }]
    });
</script>

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 360px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }
</style>

app/views/high_chart/line_charts/_basic_line.html.erb
<br />
<br />
<figure class="highcharts-figure">
    <div id="high_chart_line_charts_basic_line"></div>
    <p class="highcharts-description">
        Basic line chart showing trends in a dataset. This chart includes the
        <code>series-label</code> module, which adds a label to each line for
        enhanced readability.
    </p>
</figure>
<br />
<br />
<hr />

<script>
    Highcharts.chart('high_chart_line_charts_basic_line', {

        title: {
            text: 'Solar Employment Growth by Sector, 2010-2016'
        },

        subtitle: {
            text: 'Source: thesolarfoundation.com'
        },

        yAxis: {
            title: {
                text: 'Number of Employees'
            }
        },

        xAxis: {
            accessibility: {
                rangeDescription: 'Range: 2010 to 2017'
            }
        },

        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle'
        },

        plotOptions: {
            series: {
                label: {
                    connectorAllowed: false
                },
                pointStart: 2010
            }
        },

        series: [{
            name: 'Installation',
            data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
        }, {
            name: 'Manufacturing',
            data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
        }, {
            name: 'Sales & Distribution',
            data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
        }, {
            name: 'Project Development',
            data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
        }, {
            name: 'Other',
            data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
        }],

        responsive: {
            rules: [{
                condition: {
                    maxWidth: 500
                },
                chartOptions: {
                    legend: {
                        layout: 'horizontal',
                        align: 'center',
                        verticalAlign: 'bottom'
                    }
                }
            }]
        }

    });
</script>

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 360px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }
</style>

app/views/high_chart/line_charts/_logarithmic_axis.html.erb
<br />
<br />
<figure class="highcharts-figure">
    <div id="high_chart_line_charts_logarithmic_axis"></div>
    <p class="highcharts-description">
        This chart shows the use of a logarithmic y-axis. Logarithmic axes can
        be useful when dealing with data with spikes or large value gaps,
        as they allow variance in the smaller values to remain visible.
    </p>
</figure>
<br />
<br />
<hr />

<script>
    Highcharts.chart('high_chart_line_charts_logarithmic_axis', {

        title: {
            text: 'Logarithmic axis demo'
        },

        xAxis: {
            tickInterval: 1,
            type: 'logarithmic',
            accessibility: {
                rangeDescription: 'Range: 1 to 10'
            }
        },

        yAxis: {
            type: 'logarithmic',
            minorTickInterval: 0.1,
            accessibility: {
                rangeDescription: 'Range: 0.1 to 1000'
            }
        },

        tooltip: {
            headerFormat: '<b>{series.name}</b><br />',
            pointFormat: 'x = {point.x}, y = {point.y}'
        },

        series: [{
            data: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
            pointStart: 1
        }]
    });
</script>

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 360px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }
</style>

app/views/high_chart/line_charts/_spline_with_inverted_axes.html.erb
<br />
<br />
<figure class="highcharts-figure">
    <div id="high_chart_line_charts_spline_with_inverted_axes"></div>
    <p class="highcharts-description">
        Spline charts are smoothed line charts, and this example
        shows an inverted spline chart. Inverting the chart means the
        X-axis is positioned as the vertical axis, and the Y-axis is
        positioned as the horizontal axis. This can be more intuitive
        for certain data sets, such as in this chart where the X-axis
        represents vertical altitude.
    </p>
</figure>
<br />
<br />
<hr />

<script>
    Highcharts.chart('high_chart_line_charts_spline_with_inverted_axes', {
        chart: {
            type: 'spline',
            inverted: true
        },
        title: {
            text: 'Atmosphere Temperature by Altitude'
        },
        subtitle: {
            text: 'According to the Standard Atmosphere Model'
        },
        xAxis: {
            reversed: false,
            title: {
                enabled: true,
                text: 'Altitude'
            },
            labels: {
                format: '{value} km'
            },
            accessibility: {
                rangeDescription: 'Range: 0 to 80 km.'
            },
            maxPadding: 0.05,
            showLastLabel: true
        },
        yAxis: {
            title: {
                text: 'Temperature'
            },
            labels: {
                format: '{value}°'
            },
            accessibility: {
                rangeDescription: 'Range: -90°C to 20°C.'
            },
            lineWidth: 2
        },
        legend: {
            enabled: false
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br/>',
            pointFormat: '{point.x} km: {point.y}°C'
        },
        plotOptions: {
            spline: {
                marker: {
                    enable: false
                }
            }
        },
        series: [{
            name: 'Temperature',
            data: [[0, 15], [10, -50], [20, -56.5], [30, -46.5], [40, -22.1],
                [50, -2.5], [60, -27.7], [70, -55.7], [80, -76.5]]
        }]
    });
</script>

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 310px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }
</style>

app/views/high_chart/line_charts/_spline_with_plot_bands.html.erb
<br />
<br />
<figure class="highcharts-figure">
    <div id="high_chart_line_charts_spline_with_plot_bands"></div>
    <p class="highcharts-description">
        This demo shows how plot bands can be used on an axis to
        highlight regions of a chart. In this example, the plot
        bands are used to separate the wind speeds on the Y-axis
        into categories.
    </p>
</figure>
<br />
<br />
<hr />

<script>
    Highcharts.chart('high_chart_line_charts_spline_with_plot_bands', {
        chart: {
            type: 'spline',
            scrollablePlotArea: {
                minWidth: 600,
                scrollPositionX: 1
            }
        },
        title: {
            text: 'Wind speed during two days',
            align: 'left'
        },
        subtitle: {
            text: '13th & 14th of February, 2018 at two locations in Vik i Sogn, Norway',
            align: 'left'
        },
        xAxis: {
            type: 'datetime',
            labels: {
                overflow: 'justify'
            }
        },
        yAxis: {
            title: {
                text: 'Wind speed (m/s)'
            },
            minorGridLineWidth: 0,
            gridLineWidth: 0,
            alternateGridColor: null,
            plotBands: [{ // Light air
                from: 0.3,
                to: 1.5,
                color: 'rgba(68, 170, 213, 0.1)',
                label: {
                    text: 'Light air',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // Light breeze
                from: 1.5,
                to: 3.3,
                color: 'rgba(0, 0, 0, 0)',
                label: {
                    text: 'Light breeze',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // Gentle breeze
                from: 3.3,
                to: 5.5,
                color: 'rgba(68, 170, 213, 0.1)',
                label: {
                    text: 'Gentle breeze',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // Moderate breeze
                from: 5.5,
                to: 8,
                color: 'rgba(0, 0, 0, 0)',
                label: {
                    text: 'Moderate breeze',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // Fresh breeze
                from: 8,
                to: 11,
                color: 'rgba(68, 170, 213, 0.1)',
                label: {
                    text: 'Fresh breeze',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // Strong breeze
                from: 11,
                to: 14,
                color: 'rgba(0, 0, 0, 0)',
                label: {
                    text: 'Strong breeze',
                    style: {
                        color: '#606060'
                    }
                }
            }, { // High wind
                from: 14,
                to: 15,
                color: 'rgba(68, 170, 213, 0.1)',
                label: {
                    text: 'High wind',
                    style: {
                        color: '#606060'
                    }
                }
            }]
        },
        tooltip: {
            valueSuffix: ' m/s'
        },
        plotOptions: {
            spline: {
                lineWidth: 4,
                states: {
                    hover: {
                        lineWidth: 5
                    }
                },
                marker: {
                    enabled: false
                },
                pointInterval: 3600000, // one hour
                pointStart: Date.UTC(2018, 1, 13, 0, 0, 0)
            }
        },
        series: [{
            name: 'Hestavollane',
            data: [
                3.7, 3.3, 3.9, 5.1, 3.5, 3.8, 4.0, 5.0, 6.1, 3.7, 3.3, 6.4,
                6.9, 6.0, 6.8, 4.4, 4.0, 3.8, 5.0, 4.9, 9.2, 9.6, 9.5, 6.3,
                9.5, 10.8, 14.0, 11.5, 10.0, 10.2, 10.3, 9.4, 8.9, 10.6, 10.5, 11.1,
                10.4, 10.7, 11.3, 10.2, 9.6, 10.2, 11.1, 10.8, 13.0, 12.5, 12.5, 11.3,
                10.1
            ]

        }, {
            name: 'Vik',
            data: [
                0.2, 0.1, 0.1, 0.1, 0.3, 0.2, 0.3, 0.1, 0.7, 0.3, 0.2, 0.2,
                0.3, 0.1, 0.3, 0.4, 0.3, 0.2, 0.3, 0.2, 0.4, 0.0, 0.9, 0.3,
                0.7, 1.1, 1.8, 1.2, 1.4, 1.2, 0.9, 0.8, 0.9, 0.2, 0.4, 1.2,
                0.3, 2.3, 1.0, 0.7, 1.0, 0.8, 2.0, 1.2, 1.4, 3.7, 2.1, 2.0,
                1.5
            ]
        }],
        navigation: {
            menuItemStyle: {
                fontSize: '10px'
            }
        }
    });
</script>

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 310px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }
</style>

app/views/high_chart/more_chart_types.html.erb
<h1>HighChart#more_chart_types</h1>
<p>Find me in app/views/high_chart/more_chart_types.html.erb</p>

app/views/high_chart/pie_charts.html.erb
<h1>HighChart#pie_charts</h1>
<p>Find me in app/views/high_chart/pie_charts.html.erb</p>

app/views/high_chart/scatter_and_bubble_charts.html.erb
<h1>HighChart#scatter_and_bubble_charts</h1>
<p>Find me in app/views/high_chart/scatter_and_bubble_charts.html.erb</p>

app/views/high_chart/styled_mode.html.erb
<h1>HighChart#styled_mode</h1>
<p>Find me in app/views/high_chart/styled_mode.html.erb</p>

app/views/high_chart/three_d_charts.html.erb
<h1>HighChart#3D_charts</h1>
<p>Find me in app/views/high_chart/3D_charts.html.erb</p>

app/views/home/index.html.erb
<br><br><br>
<center><h1>High Charts :: List of Resources</h1></center>

<ul>
    <li><strong><%= link_to 'Charts - (Please Click on this link)', charts_index_path	 %></strong></li>
   <!--  <li><%#= link_to 'PDF - (In Active -> Coming Soon)', '/' %></li> -->
    <!-- <li><%#= link_to 'Charts With PDF - (In Active -> Coming Soon)', '/' %></li> -->
</ul>